### ISSUE TITLE
Error codes in php 8.2

### ISSUE THREAD

**Issue by carlosnewmusic** [aljawaid/KanboardSupport#13]
<html><body>
<div class="page-header" style="margin-top: 10px;">
        <h2>Technical Support</h2>
    </div>

    <section class="support-section">
        <h2><i class="fa fa-user"></i> User Configuration</h2>
        <div class="table-responsive">
            

User Configuration
--
```
Your Profile Full Name | Carlos | Your Role | Warning:  Trying to access array offset on value of type int in /home/blablabla/public_html/blablabla.com/plugins/KanboardSupport/Template/config/support.php on line 26 
```
```
Administrador
Your User ID | 2 | Estado | Fatal error:  Uncaught TypeError: Cannot access offset of type  string on string in  /home/blablabla/public_html/blablabla.com/plugins/KanboardSupport/Template/config/support.php:32 Stack trace: #0  /home/blablabla/public_html/blablabla.com/app/Core/Template.php(83):  include() #1  /home/blablabla/public_html/blablabla.com/app/Helper/LayoutHelper.php(207):  Kanboard\Core\Template->render('kanboardSupport...', Array) #2  /home/blablabla/public_html/blablabla.com/app/Helper/LayoutHelper.php(129):  Kanboard\Helper\LayoutHelper->subLayout('config/layout',  'config/sidebar', 'kanboardSupport...', Array) #3  /home/blablabla/public_html/blablabla.com/plugins/KanboardSupport/Controller/TechnicalSupportController.php(22):  Kanboard\Helper\LayoutHelper->config('kanboardSupport...', Array) #4  /home/blablabla/public_html/blablabla.com/app/Core/Controller/Runner.php(77):   Kanboard\Plugin\KanboardSupport\Controller\TechnicalSupportController->show() #5  /home/blablabla/public_html/blablabla.com/app/Core/Controller/Runner.php(31):  Kanboard\Core\Controller\Runner->executeController() #6 /home/blablabla/public_html/blablabla.com/index.php(9):  Kanboard\Core\Controller\Runner->execute() #7 {main}   thrown in /home/blablabla/public_html/blablabla.com/plugins/KanboardSupport/Template/config/support.php on line 32
```
</div></section>
</body>
</html>

**Comment by aljawaid** [comment]
Hello, can you please split up your errors as I cannot understand if you are reporting 1 or 2+ errors?

**Comment by aljawaid** [comment]
Also, please mention the KB version and ensure you are using the latest plugin version.

**Comment by carlosnewmusic** [comment]
> Hello, can you please split up your errors as I cannot understand if you are reporting 1 or 2+ errors?

It's the same mistake

**Comment by carlosnewmusic** [comment]
> Also, please mention the KB version and ensure you are using the latest plugin version.
KB v 1.2.32
Kanboard suport v 2.0.0

**Comment by aljawaid** [comment]
> > Also, please mention the KB version and ensure you are using the latest plugin version.
> > KB v 1.2.32
> > Kanboard suport v 2.0.0

@carlosnewmusic Please upgrade to `KanboardSupport v2.9.0` to see if the errors are resolved.  The latest release is available from GitHub and also through the Kanboard Plugins Directory
