### ISSUE TITLE
Illegal string offset

### ISSUE THREAD

**Issue by alfredbuehler** [aljawaid/KanboardSupport#2]
![image](https://user-images.githubusercontent.com/2079289/199120443-d72f5c70-5e79-4e78-9685-81bf0ad46705.png)

**Comment by aljawaid** [comment]
Cool, I will look into it... thanks for letting me know

**Comment by aljawaid** [comment]
I've spent the last hour trying to resolve this but I can't get it to work, then I thought... if the user is inactive they would not be able to login to Kanboard (I'm guessing).... so I just removed the `Status` field.  Sorry about that.
