### ISSUE TITLE
RFE: German Localization

### ISSUE THREAD

**Issue by RainerBielefeld** [aljawaid/KanboardSupport#3]
as discussed in Forum

**Comment by RainerBielefeld** [comment]
I starteda patch WiP [here](https://github.com/aljawaid/KanboardSupport/compare/master...RainerBielefeld:KanboardSupport:patch-1), will be completed next days

**Comment by RainerBielefeld** [comment]
[German_Translation_004.txt](https://github.com/aljawaid/KanboardSupport/files/9943331/German_Translation_004.txt)

Hi, can someone please integrate attached text file as KanboardSupport/Locale/de_DE/translations.php

Guthubdrives me crazy ...

**Comment by aljawaid** [comment]
> [German_Translation_004.txt](https://github.com/aljawaid/KanboardSupport/files/9943331/German_Translation_004.txt)
> 
> Hi, can someone please integrate attached text file as KanboardSupport/Locale/de_DE/translations.php
> 
> Guthubdrives me crazy ...

sure I will do it shortly
